name: Build & Publish Encryptix

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name Encryptix main.py

      - name: Check dist directory
        run: |
          echo "Contenu du dossier dist:"
          ls -la dist/ || echo "Le dossier dist n'existe pas !"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Encryptix-${{ matrix.os }}
          path: dist/Encryptix*
